apiVersion: v1
kind: Pod
metadata:
  name: redis
spec:
  containers:
  - name: redis
    image: us.gcr.io/kube-goat-prod/redis:0.1
    imagePullPolicy: Always
    env:
    - name: MASTER
      value: "true"
    ports:
    - containerPort: 6379
    lifecycle:
      postStart:
        exec:
          command: ["/init_redis.sh"]
    resources:
      limits:
        cpu: "0.1"