apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2019-04-06T16:15:48Z
  name: mist8ke.k8s.local
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    alwaysAllow: {}
  channel: stable
  cloudProvider: gce
  configBase: gs://mist8ke-configs/mist8ke.k8s.local
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-west1-a
      name: a
    name: main
  - etcdMembers:
    - instanceGroup: master-us-west1-a
      name: a
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: true
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.12.1
  masterPublicName: api.mist8ke.k8s.local
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  project: mistak-236815
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - name: us-west1
    region: us-west1
    type: Public
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-04-06T16:15:51Z
  labels:
    kops.k8s.io/cluster: mist8ke.k8s.local
  name: master-us-west1-a
spec:
  image: cos-cloud/cos-stable-65-10323-99-0
  machineType: n1-standard-1
  maxSize: 3
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-west1-a
  role: Master
  subnets:
  - us-west1
  zones:
  - us-west1-a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-04-06T16:15:55Z
  labels:
    kops.k8s.io/cluster: mist8ke.k8s.local
  name: nodes
spec:
  image: cos-cloud/cos-stable-65-10323-99-0
  machineType: n1-standard-2
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - us-west1
  zones:
  - us-west1-a