apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2019-05-20T20:03:44Z
  name: kube-goat.k8s.local
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    alwaysAllow: {}
  channel: stable
  cloudProvider: gce
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-us-central1-a
      name: a
    name: main
  - etcdMembers:
    - instanceGroup: master-us-central1-a
      name: a
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: true
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.11.1
  masterPublicName: api.kube-goat.k8s.local
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  project: {{PROJECT_ID}}
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - name: us-central1
    region: us-central1
    type: Public
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-05-20T22:13:45Z
  labels:
    kops.k8s.io/cluster: kube-goat.k8s.local
  name: master-us-central1-a
spec:
  image: cos-cloud/cos-stable-65-10323-99-0
  machineType: n1-standard-1
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-central1-a
  role: Master
  subnets:
  - us-central1
  zones:
  - us-central1-a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2019-05-20T22:13:46Z
  labels:
    kops.k8s.io/cluster: kube-goat.k8s.local
  name: nodes
spec:
  image: cos-cloud/cos-stable-65-10323-99-0
  machineType: n1-standard-2
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  fileAssets:
  - name: api-config
    path: /var/lib/google/api
    roles: [Node] 
    content: |
      the-key-18843241351
  subnets:
  - us-central1
  zones:
  - us-central1-a